fix: ai-srv OCI image build
SAP-samples/btp-cap-genai-rag pull request #16
Opened 2024-04-05 10:11 UTC by stb1337

2024-04-05 14:07 UTC, kay-schmitteckert requested changes
Thanks for your contribution. Are you willing to take a look at the comments and adjust according to it? Otherwise it's also fine that I merge the state and incorporate after.

2024-04-05 14:07 UTC, kay-schmitteckert commented on multi-tenant/code/package.json
> +        "start": "cds-serve",
shouldnt be part of the build section, rather top

2024-04-05 14:07 UTC, kay-schmitteckert commented on multi-tenant/deploy/kyma/package.json
> +    "start": "cds-serve",
not needed in the package.json for deployment

2024-04-05 14:07 UTC, kay-schmitteckert commented on single-tenant/code/package.json
> +        "start": "cds-serve",
move to top

2024-04-05 14:07 UTC, kay-schmitteckert commented on single-tenant/deploy/kyma/package.json
> +    "build:srv": "cross-env-shell pack build $IMAGE_PREFIX/ai-srv -p ../../code/gen/srv --buildpack gcr.io/paketo-buildpacks/nodejs --builder paketobuildpacks/builder-jammy-base -e BP_LAUNCHPOINT=./n
i just wonder if we still need BP_LAUNCHPOINT if we define the start script in `code/package.json`

2024-04-08 09:03 UTC, stb1337 commented on single-tenant/deploy/kyma/package.json
> +    "build:srv": "cross-env-shell pack build $IMAGE_PREFIX/ai-srv -p ../../code/gen/srv --buildpack gcr.io/paketo-buildpacks/nodejs --builder paketobuildpacks/builder-jammy-base -e BP_LAUNCHPOINT=./n
i am not sure. Lets keep it that way for the first iteration.

2024-04-08 09:38 UTC, kay-schmitteckert approved these changes

2024-04-08 09:39 UTC, merged